In [1]:
# import os
# os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
import tensorflow as tf

C:\Users\Asus\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Asus\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Asus\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Asus\AppData\Roaming\Python\Python37\site-pack

In [2]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 2117001591338480475
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 1426918195
locality {
  bus_id: 1
  links {
  }
}
incarnation: 15519761123772660666
physical_device_desc: "device: 0, name: GeForce MX150, pci bus id: 0000:01:00.0, compute capability: 6.1"
]


In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [5]:
df = pd.read_csv(r"D:\Downloads\Compressed\P16-Artificial-Neural-Networks\Artificial_Neural_Networks\Churn_Modelling.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [51]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Geography'] = le.fit_transform(df['Geography'])
le2 = LabelEncoder()
df['Gender'] = le2.fit_transform(df['Gender'])
df.head()

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602  Hargrave          619          0       0   42   
1          2    15647311      Hill          608          2       0   41   
2          3    15619304      Onio          502          0       0   42   
3          4    15701354      Boni          699          0       0   39   
4          5    15737888  Mitchell          850          2       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
x = df.iloc[: ,3:13].values
y = df.iloc[:,13].values
x,y

(array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
         1.0000000e+00, 1.0134888e+05],
        [6.0800000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
         1.0000000e+00, 1.1254258e+05],
        [5.0200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
         0.0000000e+00, 1.1393157e+05],
        ...,
        [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
         1.0000000e+00, 4.2085580e+04],
        [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
         0.0000000e+00, 9.2888520e+04],
        [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
         0.0000000e+00, 3.8190780e+04]]),
 array([1, 0, 1, ..., 1, 1, 0], dtype=int64))

In [8]:
from sklearn.model_selection import train_test_split 
xtrain , xtest , ytrain ,ytest = train_test_split(x,y,test_size = 0.2) 


In [91]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain = sc.fit_transform(xtrain)
xtest = sc.fit_transform(xtest)


array([[ 0.29732119,  1.52724663,  0.91255717, ..., -1.54405141,
        -1.03046381,  0.75259135],
       [ 0.97207502, -0.89936172, -1.09582175, ...,  0.64764683,
         0.97043679,  1.28689445],
       [-0.7303808 ,  1.52724663, -1.09582175, ...,  0.64764683,
        -1.03046381, -0.96843023],
       ...,
       [ 1.69873299, -0.89936172, -1.09582175, ...,  0.64764683,
         0.97043679, -0.11056831],
       [-1.17675641, -0.89936172, -1.09582175, ...,  0.64764683,
        -1.03046381,  0.45959035],
       [ 0.77483929, -0.89936172, -1.09582175, ..., -1.54405141,
        -1.03046381,  1.47241368]])

In [78]:
import tensorflow
import keras

In [79]:
from keras.models import Sequential
from keras.layers import Dense

In [80]:
classifier = Sequential()
classifier.add(Dense( 7 , activation = 'relu' , kernel_initializer = 'uniform',input_dim =10))
classifier.add(Dense( 7 , activation = 'relu' , kernel_initializer = 'uniform'))
classifier.add(Dense( 6 , activation = 'relu' , kernel_initializer = 'uniform'))
# classifier.add(Dense( 3 , activation = 'relu' , kernel_initializer = 'uniform'))
classifier.add(Dense(1 , activation = 'sigmoid' , kernel_initializer = 'uniform'))

In [81]:
classifier.compile(optimizer = 'adam' , loss = 'binary_crossentropy', metrics = ['accuracy'])

In [83]:
classifier.fit(xtrain , ytrain , batch_size = 32 , epochs = 20)

Epoch 1/20
8000/8000 [==============================] - 5s 574us/step - loss: 0.4245 - acc: 0.8241
Epoch 2/20
8000/8000 [==============================] - 5s 564us/step - loss: 0.4231 - acc: 0.8255
Epoch 3/20
8000/8000 [==============================] - 5s 564us/step - loss: 0.4221 - acc: 0.8262 
Epoch 4/20
8000/8000 [==============================] - 5s 564us/step - loss: 0.4208 - acc: 0.8293
Epoch 5/20
8000/8000 [==============================] - 4s 562us/step - loss: 0.4202 - acc: 0.8288
Epoch 6/20
8000/8000 [==============================] - 4s 562us/step - loss: 0.4197 - acc: 0.8297
Epoch 7/20
8000/8000 [==============================] - 5s 563us/step - loss: 0.4187 - acc: 0.8301
Epoch 8/20
8000/8000 [==============================] - 5s 566us/step - loss: 0.4177 - acc: 0.8315
Epoch 9/20
8000/8000 [==============================] - 5s 564us/step - loss: 0.4169 - acc: 0.8320
Epoch 10/20
8000/8000 [==============================] - 5s 565us/step - loss: 0.4160 - acc: 0.8326
Epoch 11

In [84]:
ypred = classifier.predict(xtest)
ypred = (ypred >0.5)
from sklearn.metrics import accuracy_score
accuracy_score(ypred , ytest)

0.8435

In [90]:
cust = np.array([[600,0,0,40,3,60000,2,1,1,50000]])
cust = sc.fit_transform(cust)

res = classifier.predict(cust)

# res = (res >0.5)
res,cust

(array([[0.31460887]], dtype=float32),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]))